apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees1
  labels : 
    app: employees
  namespace: employeesapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employeesapp
        image: 360201675659.dkr.ecr.us-east-1.amazonaws.com/my_app:v0.1
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value : 10.244.0.11
        - name: DBUSER
          value : root
        - name: DBPWD
          value : P@ssw0rd
        - name: DBPORT
          value : "3306"
