apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
  - name: db
    image: 360201675659.dkr.ecr.us-east-1.amazonaws.com/assignment2_db:v1.0
    ports: 
    - containerPort: 3306
      protocol: TCP
