apiVersion: apps/v1
kind: Deployment
metadata:
  labels :
    app: mysql
  name: mysql1
  namespace: mysqldatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqldb
        image: 360201675659.dkr.ecr.us-east-1.amazonaws.com/my_db:v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : "P@ssw0rd"
        ports: 
        - containerPort: 8080
          protocol: TCP
      
