apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: 360201675659.dkr.ecr.us-east-1.amazonaws.com/assignment2_app:v0.1
    ports: 
    - containerPort: 8080
      protocol: TCP
      apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: 360201675659.dkr.ecr.us-east-1.amazonaws.com/my_app:v0.1
    ports: 
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DBHOST
      value : 10.244.0.9
    - name: DBUSER
      value : root
    - name: DBPWD
      value : P@ssw0rd
    - name: DBPORT
      value : "3306"
      
